name: Request
description: Request to add a new game or app to the site
title: 'Add: '
labels: ['Request']

body:
  - type: input
    attributes:
      label: Name
      placeholder: 'Run 3'
    validations:
      required: true
  
      
  - type: input
    attributes:
      label: URL or repo
      placeholder: 'https://mangos.arpa/run3.html'
    validations:
      required: true
